restructure run script with functions

diff --git a/erf/run b/erf/run
--- a/erf/run
+++ b/erf/run
@@ -1,49 +1,212 @@
 #!/bin/bash
 
-# Basic run script, expects two input arguments
-# 	first one should be the name of the program being built by make
-# 	The second is the number of steps this solver will run for
+set -E
+# trap '_error_exit' ERR
+trap "echo sigkill recvd in $BASHPID" SIGKILL
 
+function _error_exit {
+	echo "Some kind of error experienced in ${BASHPID}, exiting..."
+	exit 77
+}
 
-if [[ $# != 2 ]]
-then
-	echo "Not enough arguments, exiting ..."
-	exit 1
-fi
+# Run script for different configurations
+# 	first input should always be the name of the program to compile
 
-make $1
-
-if [[ $? != 0 ]]
-then
-	echo "Make failed"
-	exit 2
-fi
-
-rm -rf RESLT/*
-
-dt=0.0001
-nx=1000
-tshift=0.0
-
-for nx in 5 10 50 80 100 500 800 1000 5000 # 10000
-# for dtp in -1 -2 -3 -4 -5
-do
-# 	dt=$(echo "10.0 ^ $dtp" | bc -l)
-	# tsteps=$(echo "$2/$dt" | bc)
-	echo -e "Running $1 with nx=$nx\t\tdt=$dt for $tsteps steps"
-	./$1 --nx $nx --vardt --tshift $tshift --tsteps $2 >> RESLT/n$nx\_t$dt.stdout &
-	# ./$1 --nx $nx --dt $dt --tshift $tshift --tsteps $2 >> RESLT/n$nx\_t$dt.stdout &
+# build function
+# $1 -> name of program (Pass in $1 from cmdline args)
+# $2 -> time scheme order (BDF number)
+# $3 -> space scheme order (NNodes per element)
+function _build {
+	CXXFLAGS=$(cat Makefile | sed -rn s/^CXXFLAGS.*=\(.*\)/\\1/p)
+	make $1 CXXFLAGS="$CXXFLAGS -DT_ORDER=$2 -DX_ORDER=$3"
 
 	if [[ $? != 0 ]]
 	then
-		echo "Run failed"
-		exit 3
+		echo "Make failed [$@]"
+		exit 1
 	fi
-done
+}
 
-wait
+# run single configuration
+# $1 -> name of program (Pass in $1 from cmdline args)
+# $2 -> number of nodes (nx)
+# $3 -> time step size (dt)
+# $4 -> number of time steps (t_steps)
+# $5 -> starting time (t_shift)
+# $6 -> output file (stdout redirect)
+function _run {
+	echo -e "Running $1 with nx=$2, dt=$3 for $4 steps in $BASHPID"
 
-echo "All processes completed"
-echo "Starting Post-processing"
+	if [[ $3 = 0.0 ]]
+	then
+		dt="--vardt"
+	else
+		dt="--dt $3"
+	fi
 
-./visualizer $1 b
+	./$1 --nx $2 $dt --tsteps $4 --tshift $5 >> $6
+	ret=$?
+
+	if [[ $ret != 0 ]]
+	then
+		echo "Run Failed"
+		exit $ret
+	fi
+
+	return $ret
+}
+
+# standard run (single config)
+# $1 -> name of program (Pass in $1 from cmdline args)
+# $2 -> number of steps (pass in $2 from cmdline args)
+function _standard {
+	T_ORDER=2
+	X_ORDER=2
+
+	_build $1 $T_ORDER $X_ORDER
+
+	rm -rf RESLT/*
+
+	nx=100
+	dt=0.0001
+	tshift=0.0
+	outfile=outfile.stdout
+
+	_run $1 $nx $dt $2 $tshift $outfile
+
+	./visualizer $1 a
+}
+
+function _dx_analysis {
+	T_ORDER=2
+	dt=0.0001
+	tshift=0.0
+	
+	rm -rf RESLT/*
+	
+	pids=()
+	for X_ORDER in 2 # 3 4
+	do
+		rm $1
+		_build $1 $T_ORDER $X_ORDER
+
+		for nx in 5 10 50 80 100 500 800 1000 5000
+		do
+			stdoutfile="RESLT/${X_ORDER}x${nx}_${T_ORDER}t${dt}.stdout"
+			echo $stdoutfile
+			_run $1 $nx $dt $2 $tshift $stdoutfile &
+			pids+="$! "
+		done
+
+		for pid in $pids
+		do
+			wait $pid
+
+			if [[ $? != 0 ]]
+			then
+				echo "run failed in dx analysis, exiting..."
+				kill 0
+				exit 1
+			fi
+		done
+	done	
+
+	./visualizer $1 x
+}
+
+function _dt_analysis {
+	X_ORDER=2
+	nx=1000
+	tshift=0.0
+	
+	rm -rf RESLT/*
+	
+	pids=()
+	for T_ORDER in 1 2 # 4
+	do
+		rm $1
+		_build $1 $T_ORDER $X_ORDER
+
+		for dtp in -1 -2 -3 -4 -5
+		do
+			dt=$(echo "10.0 ^ $dtp | bc -l")
+			tsteps=$(echo "$2/$dt | bc")
+			stdoutfile="RESLT/${X_ORDER}x${nx}_${T_ORDER}t${dt}.stdout"
+
+			echo $stdoutfile
+			_run $1 $nx $dt $tsteps $tshift $stdoutfile &
+			pids+="$! "
+		done
+
+		for pid in $pids
+		do
+			wait $pid
+
+			if [[ $? != 0 ]]
+			then
+				echo "run failed in dx analysis, exiting..."
+				kill 0
+				exit 1
+			fi
+		done
+	done	
+
+	./visualizer $1 t
+}
+
+function _dxdt_analysis {
+	T_ORDER=2
+	dt=0.0
+	tshift=0.0
+	
+	rm -rf RESLT/*
+	
+	pids=()
+	for X_ORDER in 2 # 3 4
+	do
+		rm $1
+		_build $1 $T_ORDER $X_ORDER
+
+		for nx in 5 10 50 80 100 500 800 1000 5000
+		do
+			stdoutfile="RESLT/${X_ORDER}x${nx}_${T_ORDER}t${dt}.stdout"
+			echo $stdoutfile
+			_run $1 $nx $dt $2 $tshift $stdoutfile &
+			pids+="$! "
+		done
+
+		for pid in $pids
+		do
+			wait $pid
+
+			if [[ $? != 0 ]]
+			then
+				echo "run failed in dx analysis, exiting..."
+				kill 0
+				exit 1
+			fi
+		done
+	done	
+
+	./visualizer $1 b
+}
+
+function _main {
+	if [[ $# != 3 ]]
+	then
+		echo "Invalid number of arguments, exiting"
+		exit 1
+	fi
+
+	echo "Main running in $BASHPID"
+
+	case $3 in
+		"a") _standard $@ ;;
+		"x") _dx_analysis $@ ;;
+		"t") _dt_analysis $@ ;;
+		"b" | "xt") _dxdt_analysis $@ ;;
+		*) echo "Unknown profile" ;;
+	esac
+}
+
+_main "$@"
