update scripts to run multiple configs in parallel

diff --git a/erf/run b/erf/run
--- a/erf/run
+++ b/erf/run
@@ -21,12 +21,15 @@ fi
 
 rm -rf RESLT/*
 
-./$1 --nx 10 --dt 0.01 --tsteps $2
+for i in 10 100
+do
+	./$1 --nx $i --dt 0.01 --tsteps $2 | tee RESLT/$i.stdout &
 
-if [[ $? != 0 ]]
-then
-	echo "Run failed"
-	exit 3
-fi
+	if [[ $? != 0 ]]
+	then
+		echo "Run failed"
+		exit 3
+	fi
+done
 
 ./visualizer $1 $2
